service: currenttime

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  memorySize: 128
  timeout: 30

functions:
  api:
    handler: handler.handler
    timeout: 300
    events:
      - http:
          path: /
          method: GET