name: Current-Time-Deploy

on:
  push:
    branches: [main]

jobs:
  deployment: 
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Serverless Framework
        run: npm install -g serverless@3.38.0-d09dc659

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy Lambda function
        run: serverless deploy --stage dev --region us-east-2